#[build]
#	functions = "functions/"
#[dev]
#  functions = "functions/"

#[[headers]]
#  # Define which paths this specific [[headers]] block will cover.
#  for = "/*"
#    [headers.values]
#    Access-Control-Allow-Origin = "*"

#[[plugins]]
#  package = "@netlify/plugin-functions-install-core"

[[redirects]]
  from = "/events"
  to = "/creates"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200